# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        ('skill', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('DOB', models.DateTimeField()),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
                ('experience', models.IntegerField(default=1)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentDetails')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.ManagerDetail')),
                ('skills', models.ManyToManyField(to='skill.SkillDetails')),
            ],
        ),
    ]
