# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('DOB', models.DateTimeField()),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
                ('experience', models.IntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('experience', models.IntegerField(default=1)),
                ('DOB', models.DateTimeField()),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.skills'),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.manager'),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.skills'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_app.manager'),
        ),
    ]
