# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0003_auto_20181118_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skills',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
