# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0004_auto_20181118_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample_app.manager'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample_app.Department'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample_app.manager'),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='sample_app.skills'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='sample_app.skills'),
        ),
    ]
