# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0005_auto_20181118_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='skills',
            field=models.ManyToManyField(to='sample_app.skills'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='skills',
            field=models.ManyToManyField(to='sample_app.skills'),
        ),
    ]
