# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0007_auto_20181118_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
