# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0009_auto_20181118_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
