# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0010_auto_20181118_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='id',
            new_name='dep_code',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='id',
            new_name='emp_id',
        ),
    ]
