# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0011_auto_20181121_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_details',
            new_name='Employee_detail',
        ),
        migrations.RenameModel(
            old_name='skills',
            new_name='skill',
        ),
    ]
