# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0013_auto_20181121_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_detail',
            new_name='EmployeeDetail',
        ),
    ]
