# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0017_auto_20181122_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='skills',
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample_app.Manager'),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample_app.Manager'),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='skills',
            field=models.ManyToManyField(to='sample_app.Skill'),
        ),
    ]
